apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: default
spec:
  encryptedData:
    api-key: AgAM3sclQWqk8iZ/vjcgTU1HrNTCwC4dZEOMmtU+oX5rjDu2UN7bUX/9GSvBzmf3klikvpu3s24gbYSQcXh16B0TyYwcEr5ck3rSihOFYGb9FKGvQahkWOZWvmWCt0HQ/DxCOGv8yh/4eFMK2nhDuhMs1+wVPatteDnsIOXl9QGA+Io/vsyPkUvmWO+EiHG42faYno61X0tV3LjzopMowaesJkeSgqVCPmjM53WSCK4irnnjInhtXlf3ipAd+ZHQ5IgRGzlNiwtDKukBmh+B12kTLlIFEeN+tGoI6VaBnOGjuAIkN434J1wc3MKIw8fon/il19HpUaFsTrnjIIPcqr1t4yL20G+rRAwf7Y7dtd9YMFr1pYUvDa1EVE0K1fderTCM/NG8hzb+a22QC/uRNsk+xfiU4fxZuybDwfzSnWGvDokHeraxQMO7je5mw5chuCYJLF2r0YRTy1LK6/KnE1Ovy4zQMC3vQLRV9Za97ysf+cijcLZK8VnqI/XXGh/0RYgMXXMMzBI4br8ZutRK066cXC96C9wtMJhtZW08+xJjclZOQgy9MjztaUICDgY2zKy8Pc5QwzJlIvplYXEEm13RLCY8ozzw3i55m5UqvKGLWAg1v+EbZeQTnQzRE0EOT6rZM54d3ewvtvZ3LuvarJAP/recPr2yM3zB0XFv0VRYcza1L/bRZ/Ec0NnYORMGNaxEsiK4tCu/nMo=
    db-password: AgBZDbXoLqKJmy1LhCySgnlwL60dfsY62/VQdWF+/i4OrSirEFi1BqUbCW2Yo7PSdDT/yLwPv5yJLBXFL7VSiYi9UuQtfHDbFGD8LcZWwjCjxg5C5dxWdZ3vxHp4e26UNZMzAu0vkboim9FuC4O+akSCZk7M/o7amxDNailyWc/mR5Tl2Z/5KuwTzZke8XRcm0S70/rjH753J9ogkiVM4OuzIiF6xhy2cEx0SCCsHWIGMBp1kuQ66Wuzimb3PXa5iAh+JiXpeZ2tUyzOY9Vxb7Jm+O4gQOSyY9xZm6jsUYC2TN/rP2oVnd1qFs3sG/IjKSu33wP1evp8xrFxnH2YvtWKKVjCwERfXCSvwBzQJKaYxbg9E4CoVAnfXFzzFBzfO9f1rGzcoXIGTrGoUmqz7kWsOPnYdZH/j8hLHjocKTLc6cBx1wHPgbafvDcd6LzQ8AaW0cn4s5oCVKbECxcaSZp6ak9Q6bPOb/EM7rPkD72FKn5i9KVH2rzd3NXfB2VmBUC6SGRL4k80ZruQpxVzXRC7GayQLlGD2syWZihRwEnnMh1iJc6I7fLFpGHujcGp9hG07+DsKRcaTf/BhmhAbxHimqIsSa/p7NqSAkahKoHcaQzRO4+XjVEdalim9xJhVE+MrQOwM8FPJTyE/Te5Kju2bDPe/XAsaa87ucMuzTEQQ89hicQCM43hrtZ9Yacn1evzm3+cZblQAu3yoSI=
  template:
    metadata:
      creationTimestamp: null
      name: app-secrets
      namespace: default
---
