apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-secrets
  namespace: default
spec:
  encryptedData:
    api-key: AgAX/b8b1fxJpXTbMLSYZyREQEiqaAecfl2tHIeA7dPXLKYbzo1yzmBp/Nxko7kRPPP0Mjnfbz7JSC5lDIkQge52hF6sdh6NL1tftdodRO/rBuNlfDATsep6n0G0mnviOfystdYPHczejnNq2pyBSUVTxCOFp3czHUc7MTXQUehLDYV/Fy7bSSkenVD0DgGNHmZLvKl5JEKUOOJhN/2O4xicXt9q78/IUtQ+G/8eLDbVvWIQTt68JPorMkzz8g2HCdg0pTOijLuyjDOxs0I9CdQQiZRNzka1nAQZWwTNWCTc+ETvge0viuZHPJxBv59wrfsYCFjtg5r3ta9Z5J/nRx2X6mset6rtfUfiP5EH6ykDpFQYxTVnwO3f4etwVt8ZCP4sbBwn7Mova/3uZyoeZOmm35hDiDmhhuRe9FPBU8DYBWcNvDlvDBwmrxtSTSwABuRBTSzy4+71p24NReHs/jA3sdMUEJF7Tl5wxMUu0CHB4cS3oaa3aj1gtLoIBu5J4mLRSG4D2+soPe6wAbgGYsv73wIUS/oZdI2YgMwX+mMwfv85WIsEV4CtDvkiRbix06cb/EmH2bLoi1hMvbrKDs4u1czf22Grz6vH59AxbPk++IZ9Lg8G7kNfDVrTbMa3b+UXZdPQPvkAAvQy/ZrW/IvlcarMXV9jNwi3EIU2rwrEArhYvJRRx8tGYIHN8WHOzZRHRmoWqbUBKe+nPw==
    db-password: AgCly7ZhLigtEaLjId7+S6DKQvLJuIT/I7hdS9HoJcy2cJxkl+WX56DzuHnbAGfUpJZcaiDJPxUwOqx7fqIrgxrshVz8l+e6ZbUX1UStSRK4QYdAGLKq5SznCfEsjArs1f3AKdUwLgkZz+D77ay1/KCdE8muDaRqPy67B1D+AW+GneKS4MuX5Fy6TmcK8jSjZ8dICMYb2eO7qLElq3+qA/bCao7ObXIa1UoWqy0wABirJhvZkDCPt/8+hsnSwngLSd/Qp5lc2LWPbh6ICAXqKgSSGfX63ucwtP4STVyerTv24oNUPx6VSUR61p2VgR1QLgcFxu3g+TXVKDoeu2zads+ehDKHsAKF/CSI9I/L5mgL8GJv70HIiJO9dHJjZgtXxsjygzoLR5PjK5VJYDg0bK7cC+RfuY1DNL7BbsT9Yd/Jd/d5KCC+DhPN0K3K/fJcUoOrYHNLBOc9Wa0MlYBiEeW+sCLOd8SJO84/E5KoEa3cjgxWg4c3tIu1I3dFexSC4vqWrCEOi+A6vneZH8jm1BNn/Goku6sRhFp5pm6uNzJaLrXlaf5vLtdxfth54QgWKH5XhDjaec9gPY1zI+xB5pYnniMC8mG/w3qS5S36t04ku5Qweiezmm7FEuJZM41/4EA+4NL04c9x6WzIkMrlWyRp3wQt7tCvdG3WpNuzZb7V1r0B81LlZ4a6y8Fq/5UCOrjzVGPwOKqPJIRkIFN86w==
  template:
    metadata:
      creationTimestamp: null
      name: app-secrets
      namespace: default
---
